version: "3"
services:
  nginx:
    image: ldirer.com/nginx-static
    build:
      dockerfile: nginx.dockerfile
      context: ./deploy
    environment:
      # nginx-proxy stuff!
      - VIRTUAL_HOST=ldirer.com
